export const certificates = [
  {
    id: 1,
    number: '01',
    title: 'Oracle Certified Professional',
    organization: 'Oracle',
    platform: 'Certification',
    year: '2023',
    description: 'Comprehensive validation of advanced skills in database management, administration, and performance tuning, demonstrating expertise in complex relational database environments.',
    tags: ['Database', 'SQL', 'Administration'],
    fileUrl: '/certificates/oracle certificate.png',
    certificateUrl: '/certificates/oracle certificate.pdf',
    type: 'image',
  },
  {
    id: 2,
    number: '02',
    title: 'Python for Data Science',
    organization: 'IBM / Coursera',
    platform: 'Data Science',
    year: '2024',
    description: 'In-depth mastery of Python data structures, pandas for data manipulation, and fundamental machine learning techniques, showcasing ability to develop data-driven solutions.',
    tags: ['Python', 'Data Science', 'Pandas'],
    fileUrl: '/certificates/Python for Data Science.png',
    certificateUrl: '/certificates/Python for Data Science.pdf',
    type: 'image',
  },
  {
    id: 3,
    number: '03',
    title: 'Database Management System',
    organization: 'Institute',
    platform: 'DBMS',
    year: '2023',
    description: 'Extensive study of relational database concepts, sophisticated schema design practices, and advanced query optimization strategies, equipping me to build efficient data systems.',
    tags: ['DBMS', 'SQL', 'Schema Design'],
    fileUrl: '/certificates/Data Base Management System (1).png',
    certificateUrl: '/certificates/Data Base Management System (1).pdf',
    type: 'image',
  },
  {
    id: 4,
    number: '04',
    title: 'Hackathon Winner',
    organization: 'Hackathon',
    platform: 'Competition',
    year: '2024',
    description: 'Recognized with first place for designing and implementing an innovative AI architecture solution that leveraged cutting‑edge technologies to solve complex problems.',
    tags: ['Hackathon', 'AI', 'Innovation'],
    fileUrl: '/certificates/hackathon winner.png',
    certificateUrl: '/certificates/hackathon winner.pdf',
    type: 'image',
  },
];
