export const training = [
  {
    id: 1,
    number: '01',
    title: 'IBM SkillsBuild',
    organization: 'IBM',
    platform: 'SkillsBuild',
    year: '2024',
    description: 'Completion of advanced IBM SkillsBuild training program covering enterprise architecture.',
    tags: ['Enterprise', 'Architecture', 'IBM'],
    fileUrl: '/training_certificates/Completion Certificate _ SkillsBuild -3.png',
    certificateUrl: '/training_certificates/Completion Certificate _ SkillsBuild -3.pdf',
    type: 'image',
  },
  {
    id: 2,
    number: '02',
    title: 'IBM Final Certificate',
    organization: 'IBM',
    platform: 'Certification',
    year: '2024',
    description: 'Final certification covering intensive cloud and systems integration methodologies.',
    tags: ['Cloud', 'Systems', 'Integration'],
    fileUrl: '/training_certificates/IBM final certificate.png',
    certificateUrl: '/training_certificates/IBM final certificate.pdf',
    type: 'image',
  },
  {
    id: 3,
    number: '03',
    title: 'Indian Space Research',
    organization: 'ISRO',
    platform: 'Workshop',
    year: '2023',
    description: 'Specialized workshop on spatial data processing and telemetry analytics.',
    tags: ['Space', 'Telemetry', 'Analytics'],
    fileUrl: '/training_certificates/Indian space crop.png',
    certificateUrl: '/training_certificates/Indian space crop.pdf',
    type: 'image',
  },
  {
    id: 4,
    number: '04',
    title: 'PBL Certificate',
    organization: 'Project Based Learning',
    platform: 'PBL',
    year: '2023',
    description: 'Hands-on project based learning program completing a full lifecycle deployment.',
    tags: ['PBL', 'Deployment', 'Lifecycle'],
    fileUrl: '/training_certificates/pbl certificate (1).png',
    certificateUrl: '/training_certificates/pbl certificate (1).pdf',
    type: 'image',
  },
];
